config/routes.rb
Rails.application.routes.draw do
  resources :pins

 
  devise_for :users
  root "pages#games"

  get "prix" => "pages#prix"
get "blog" => redirect("http://dysactu.wordpress.com")

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
          has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
    # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user_subscribed?
    user_signed_in? && current_user.subscribed?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 50)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "DYS", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Blog", blog_path %></li>

         <li>
            <%= link_to prix_path do %>
              <span class="glyphicon glyphicon-plus"></span> Prix
            <% end %>
          </li>
        <% if user_signed_in? %>

          
          <li><%= link_to "deconnexion", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Connexion", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DYS</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
mixpanel.init("31eb096369e93fedcc792433a9967c7f");</script><!-- end Mixpanel -->
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <h1>Platforme DYS </h1>
  <h2>Solution pour combattre la Dyslexie </h2>

     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Connexion", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Inscription Gratuite", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>



  <div class="prez center">
            <object width="1000" height="1000">
        <param name="movie" value="https://www.youtube.com/v/N83TFsZhLfU?rel=0"></param>
        <param name="allowFullScreen" value="true"></param>
        <embed src="https://www.youtube.com/v/N83TFsZhLfU?rel=0&amp;controls=0&amp;showinfo=0" type="application/x-shockwave-flash" allowfullscreen="true" width="600" height="400"></embed>

</object>

              </div>

</div>

app/views/pages/blog.html.erb
<style>
.imagg{
	margin-left: auto;
	float: left;

}
.tex{
	margin-right: auto;

}
</style>
<div class="jumbotron">
	 <%= image_tag("blog.jpg",:size => "225x149", :class=> "imagg") %>
<div class="tex"><p> Lorem Khaled Ipsum is a major key to success. The key to success is to keep your head above the water, never give up. They will try to close the door on you, just open it. The other day the grass was brown, now it’s green because I ain’t give up. Never surrender. Major key, don’t fall for the trap, stay focused. It’s the ones closest to you that want to see you fail. <%= link_to "en savoir plus", "http://dysactu.wordpress.com" %> </p>
</div>
</div>

app/views/pages/games.html.erb
<%= render 'pages/home' unless user_signed_in? %>


<div class="jumbotron">



<% b = {id: 1,
      question: "ça marche ?",
      reponse: "oui" }
 %>
  <!-- <h1> <%= b[:question] %> </h1>
</br>
<%= form_tag "reponse"  %>

<%= text_field_tag :rep ,  nil, :placeholder => 'reponse' %>
-->
    <% # If :rep = b[:reponse]
    #  z="ouiiiiiii"
    # else
    #  z="non!"
    # end
     %>
    <!-- <h1>  </h1> -->

<h1> Lire à haute voix </h1> </br>
<p> rang - rein - rien - rond - ronde - raie - rire </br>
   sien - chien - lien - loin - lin </br>
   main - moins -mieux -mien  </br>
   loin - lieu - lien - loig </br>
   fuir - nuire - suie - suite - suivre </br> </p>



<div>

app/views/pages/prix.html.erb
<link rel="stylesheet" href="css/reset.css"> <!-- CSS reset -->
	<link rel="stylesheet" href="css/style.css"> <!-- Resource style -->
	<script src="js/modernizr.js"></script> <!-- Modernizr -->

<div class="jumbotron">
	<h1>Bienvenue sur la platforme DYS </h1>
	<div class="cd-pricing-container cd-full-width cd-secondary-theme">
			<ul class="cd-pricing-list">
				<li>
					<header class="cd-pricing-header">
						<h2>Basic</h2>

						<div class="cd-price">
							<span class="cd-currency">€</span>
							<span class="cd-value">0</span>
							<span class="cd-duration">mois</span>
						</div>
					</header> <!-- .cd-pricing-header -->

					<div class="cd-pricing-body">
						<ul class="cd-pricing-features">
							<li><em>Accès</em> illimité </li>
							<li><em>pas</em> de statistique </li>
							<li><em>pas</em> de suivie</li>
							<li><em>support</em> limité</li>
						</ul>
					</div> <!-- .cd-pricing-body -->

					<footer class="cd-pricing-footer">
					<%= link_to "Inscription Gratuite", new_user_registration_path, class: "btn btn-primary btn-lg" %>
					</footer> <!-- .cd-pricing-footer -->
				</li>
				<li class="cd-popular">
					<header class="cd-pricing-header">
						<h2>Courageux</h2>

						<div class="cd-price">
							<span class="cd-currency">€</span>
							<span class="cd-value">4.99</span>
							<span class="cd-duration">mois</span>
						</div>
					</header> <!-- .cd-pricing-header -->

					<div class="cd-pricing-body">
						<ul class="cd-pricing-features">
							<li><em>Accès</em> illimité </li>
							<li><em>statistique</em>  </li>
							<li><em>suivie</em> </li>
								<li><em>24h/7j</em> Support</li>
						</ul>
					</div> <!-- .cd-pricing-body -->

					<footer class="cd-pricing-footer">
					<%= link_to "Je suis Courageux", new_user_registration_path, class: "btn btn-primary btn-lg" %> </footer> <!-- .cd-pricing-footer -->
				</li>
				<li>
					<header class="cd-pricing-header">
						<h2>Déterminer</h2>

						<div class="cd-price">
							<span class="cd-currency">€</span>
							<span class="cd-value">20</span>
							<span class="cd-duration">mois</span>
						</div>
					</header> <!-- .cd-pricing-header -->

					<div class="cd-pricing-body">
						<ul class="cd-pricing-features">
							<li><em>Accès</em> illimité </li>
							<li><em>statistique</em> et prévition </li>
							<li><em>suivie</em> Quotidient </li>
								<li><em>24h/7j</em> Support</li>
									<li><em>Test</em> de performance  </li>
						</ul>
					</div> <!-- .cd-pricing-body -->

					<footer class="cd-pricing-footer">
					<form action="/charge" method="POST">
					  <script
					    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
					    data-key="pk_live_TBwrLbZnO46ITjq92xxUXm07"
					    data-image="/img/documentation/checkout/marketplace.png"
					    data-name="cyril"
					    data-description="Compte Déterminer"
					    data-currency="eur"
					    data-amount="100"
					    data-locale="auto">
					  </script>
					</form>
						</BR>
	<h3>Si </BR> en 1ans il n'y a pas de progrès </BR> Remboursement </h3>
					</footer>  <!-- .cd-pricing-footer -->

				</li>
			</ul> <!-- .cd-pricing-list -->

		</div> <!-- .cd-pricing-container -->
		<script src="js/jquery-2.1.1.js"></script>
		<script src="js/main.js"></script> <!-- Resource jQuery -->
	<script type="text/javascript">
  Stripe.setPublishableKey('pk_live_TBwrLbZnO46ITjq92xxUXm07');
	</script>

</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= image_tag pin.image.url(:medium) %></td>
        <td><%= pin.description %></td>
        <td><%= pin.user.email if pin.user %></td>
        <td><%= link_to 'Show', pin_path(pin) %></td>
        <% if pin.user == current_user %>
          <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
          <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path %>
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
		<div class="panel-heading center">
			<%= image_tag @pin.image.url %>
		</div>
		<div class="panel-body">
		<p><%= @pin.description %></p>
		<p><strong><%= @pin.user.name if @pin.user %></strong></p>

		<% if @pin.user == current_user %>
			<%= link_to edit_pin_path(@pin) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
		<% end %>
		</div>
	</div>

</div>

app/views/surveys/_answer_fields.html.erb
<p>
  <%= f.label :content, "Answer" %>
  <%= f.text_field :content %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove" %>
</p>